### ISSUE TITLE
Game uses 4-5 gigabytes of memory, causing tons of memory leaks and black squares

### ISSUE THREAD

**Issue by benjaminpants** [KadeDev/trickster#3]
Using the windows build, latest version at the time of this post, the game uses 4 gigabytes and gets worse as you play through the songs.
Here is an image I took during Song 3, the tricky sprite refused to load and the memory usage increased by 200 every time I tried reloading to fix the black squares
![image](https://user-images.githubusercontent.com/27522994/120544512-5ac65e00-c3a2-11eb-8fe1-a0a02924b16a.png)
And here is how much memory it uses just IDLING.
This is ridiculous.
![image](https://user-images.githubusercontent.com/27522994/120544595-7467a580-c3a2-11eb-8598-263acbfdb670.png)

**Comment by KadeDev** [comment]
cuz we're saving a shit ton of crap into memory. how about you get a better pc nerd!

**Comment by benjaminpants** [comment]
I have 16 gigabytes of ram and it still doesn't load

**Comment by KadeDev** [comment]
idk smth in ur setup is being bad. everyone on the dev team can play it just fine.

**Comment by hatechara19** [comment]
can I have link

**Comment by moldycheese99** [comment]
i think i know why it happens the freaking hellclown idle is 15 megabytes and its a 10000x10000 image LMAO

**Comment by benjaminpants** [comment]
> 
> 
> idk smth in ur setup is being bad. everyone on the dev team can play it just fine.

my system stats
![image](https://user-images.githubusercontent.com/27522994/120591869-b9ff8f00-c3f1-11eb-909f-48eb30bde480.png)

along with an Geforce GTX 980, i can play the mod but I have to close everything.

Please, downscale the Hellclown sprites literally no one will notice

**Comment by TheEssem** [comment]
> cuz we're saving a shit ton of crap into memory. how about you get a better pc nerd!

This is an awful response to an issue like this. There is clearly a memory allocation issue with this software that occurs on both low- and high-end PCs and instead of doing something about it, you mock the people that bring it up. Most of the memory taken up is with a single sprite set that loses most of its detail when viewed ingame; maybe you should focus on that instead of telling people to get a new, high-end PC to run a game that exclusively uses 2D sprites?

Do better.

**Comment by ACrazyTown** [comment]
Seems to be pretty mixed, I have an old workstation from like 2010 with 2x Intel Xeons, 12GB of DDR3 RAM and a GTX 1050 and the game works fine for me

**Comment by TheGoodGarfunkel** [comment]
This is a 2D game.
Garry's Mod is a 32-bit game that runs on a maximum of 4GB and barely reaches that limit.
It is a 3D game that uses 5 times less memory than this mod.
For a mod that can crash about half the time on the loading screen, you should look at your glaringly obvious memory allocation issues instead of:
`how about you get a better pc nerd!`
